FROM gcc:latest
RUN git clone -q https://github.com/Margaret-Alade/task_5.2-threads.git /Users/margaret/Desktop/student homework/task_5.2
WORKDIR /Users/margaret/Desktop/student homework/task_5.2
RUN g++ -o Task5 main.cpp
CMD ["./Task5"]

